apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
  namespace: cka-task2
spec:
  containers:
  - image: nginx
    name: nginx
    command: ["/bin/sh","-c","sed -i 's/listen  .*/listen 8080;/g' /etc/nginx/conf.d/default.conf && exec nginx -g 'daemon off;'"]
    ports:
    - containerPort: 8080
      name: http
      protocol: TCP
